# Generated by Django 4.2.6 on 2023-11-17 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(max_length=20)),
                ('princi_app', models.BooleanField(default=False)),
                ('admin_app', models.BooleanField(default=False)),
                ('ac_paid', models.CharField(choices=[('free', 'free'), ('paid', 'paid')], max_length=20)),
                ('reason_princi', models.TextField()),
                ('reason_admin', models.TextField()),
                ('is_approved', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='media_req',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('reason', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.CharField(max_length=2)),
                ('time_period', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('AC', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking_request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('program_title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('requested_dep', models.CharField(max_length=200)),
                ('ac', models.BooleanField(default=False)),
                ('coordinator', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=10)),
                ('participants', models.PositiveIntegerField()),
                ('level', models.TextField(choices=[('National', 'National'), ('State', 'State'), ('College', 'College')])),
                ('sponsor', models.CharField(max_length=100)),
                ('chief_guest', models.CharField(max_length=100)),
                ('program_obj', models.TextField(max_length=100)),
                ('media', models.TextField(choices=[('photo', 'Photo'), ('video', 'Video'), ('both', 'Both Photo and Video'), ('none', 'No Media')])),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_queue', models.BooleanField(default=False)),
                ('slots', models.ManyToManyField(blank=True, to='booking.slots')),
                ('venue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking_postpone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(max_length=20)),
                ('date', models.DateField(null=True)),
                ('slots', models.ManyToManyField(blank=True, to='booking.slots')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
