# Generated by Django 4.2.5 on 2023-09-09 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='program_level',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.IntegerField()),
                ('time_period', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='venue',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('ac_or_not', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('program_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('requested_dep', models.CharField(max_length=200)),
                ('coordinator', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('expected_no_of_participants', models.PositiveIntegerField()),
                ('sponsor', models.CharField(max_length=100)),
                ('chief_guest', models.CharField(max_length=100)),
                ('objective_of_programme', models.TextField()),
                ('status', models.BooleanField()),
                ('level', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.program_level')),
                ('media_coverage', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.media')),
                ('time_slots', models.ManyToManyField(blank=True, to='booking.slots')),
                ('venue', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
