# Generated by Django 4.2.6 on 2024-07-22 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_number', models.CharField(default=uuid.uuid4, editable=False, max_length=10, unique=True)),
                ('program_title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('requested_dep', models.CharField(max_length=200)),
                ('ac', models.BooleanField(default=False)),
                ('coordinator', models.CharField(blank=True, max_length=200)),
                ('contact_no', models.CharField(blank=True, max_length=10)),
                ('participants', models.PositiveIntegerField(blank=True)),
                ('sponsor', models.CharField(blank=True, max_length=100)),
                ('chief_guest', models.CharField(blank=True, max_length=100)),
                ('program_obj', models.TextField(blank=True, max_length=100)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_queue', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_postpone', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media_sel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(max_length=2)),
                ('time_period', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('AC', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='media_req',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking_request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking_request',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.levels'),
        ),
        migrations.AddField(
            model_name='booking_request',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.media_sel'),
        ),
        migrations.AddField(
            model_name='booking_request',
            name='slots',
            field=models.ManyToManyField(blank=True, to='booking.slots'),
        ),
        migrations.AddField(
            model_name='booking_request',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.venue'),
        ),
        migrations.CreateModel(
            name='Booking_postpone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking_request')),
                ('slots', models.ManyToManyField(blank=True, to='booking.slots')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking_approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('princi_app', models.CharField(default='pending', max_length=20)),
                ('admin_app', models.CharField(default='pending', max_length=20)),
                ('ac_paid', models.CharField(blank=True, choices=[('free', 'free'), ('paid', 'paid')], max_length=20)),
                ('reason_princi', models.TextField(blank=True)),
                ('reason_admin', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_postpone', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking_request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
