# Generated by Django 4.2.5 on 2023-09-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='ac_or_not',
            new_name='AC',
        ),
    ]
