# Generated by Django 4.2.6 on 2023-11-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_approval',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking_request'),
        ),
    ]
