# Generated by Django 4.2.6 on 2023-11-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_approval_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_postpone',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking_request'),
        ),
        migrations.AlterField(
            model_name='media_req',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking_request'),
        ),
    ]
