# Generated by Django 4.1.7 on 2023-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_ac_or_not_venue_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
