# Generated by Django 4.2.6 on 2023-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_postpone_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_request',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
