# Generated by Django 4.2.5 on 2023-09-17 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_details_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked_slots',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('venue_name', models.CharField(max_length=100)),
                ('book_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='booking_details',
            new_name='booking_request',
        ),
    ]
