# Generated by Django 4.2.5 on 2023-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booked_slots_rename_booking_details_booking_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_request',
            name='media_coverage',
        ),
        migrations.AddField(
            model_name='booking_request',
            name='media_coverage',
            field=models.ManyToManyField(blank=True, to='booking.media'),
        ),
    ]
