# Generated by Django 4.1.7 on 2023-09-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_request_media_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_request',
            name='media_coverage',
        ),
        migrations.AddField(
            model_name='booking_request',
            name='media_selection',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('both', 'Both Photo and Video'), ('none', 'No Media')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='level',
            field=models.CharField(choices=[('National', 'National'), ('State', 'State'), ('College', 'College')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.venue'),
        ),
        migrations.DeleteModel(
            name='media',
        ),
        migrations.DeleteModel(
            name='program_level',
        ),
    ]
