# Generated by Django 4.2.6 on 2023-11-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_levels_media_sel_alter_booking_request_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_request',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
