# Generated by Django 4.1.7 on 2023-09-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_request_media_coverage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booked_slots',
        ),
    ]
