# Generated by Django 4.1.7 on 2023-09-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_delete_booked_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='slot',
            field=models.CharField(max_length=2),
        ),
    ]
