# Generated by Django 4.1.7 on 2023-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_approval_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_approval',
            name='ac_paid',
            field=models.CharField(blank=True, choices=[('free', 'free'), ('paid', 'paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking_approval',
            name='reason_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking_approval',
            name='reason_princi',
            field=models.TextField(blank=True),
        ),
    ]
