# Generated by Django 4.1.7 on 2023-11-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_approval_ac_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_request',
            name='chief_guest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='coordinator',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='participants',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='program_obj',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='sponsor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
