# Generated by Django 4.1.7 on 2023-09-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_levels_media_alter_booking_request_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_request',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='levels',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='slots',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='uid',
            new_name='id',
        ),
    ]
