# Generated by Django 4.2.5 on 2023-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_uid_booking_request_id_rename_uid_levels_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_request',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking_request',
            name='program_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
