# Generated by Django 4.1.7 on 2023-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_request_chief_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_approval',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='booking_approval',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking_approval',
            name='admin_app',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking_approval',
            name='princi_app',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
