# Generated by Django 4.2.5 on 2023-09-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_request_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_request',
            name='ac',
            field=models.BooleanField(default=False),
        ),
    ]
