# Generated by Django 4.2.6 on 2023-11-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_approval_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_request',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
