# Generated by Django 4.2.6 on 2023-11-26 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_request_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_request',
            name='booking_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
    ]
