# Generated by Django 4.2.6 on 2023-12-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_request_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_approval',
            name='is_postpone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking_request',
            name='is_postpone',
            field=models.BooleanField(default=False),
        ),
    ]
