# Generated by Django 4.2.6 on 2023-12-30 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_approval_is_postpone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_request',
            name='booking_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, unique=True),
        ),
    ]
